version: "2"
services:
  um1:
    image: mariadb/columnstore:1.2
    environment:
      - MARIADB_CS_POSTCFG_INPUT=
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_USER=jupiter_user
      - MARIADB_PASSWORD=jupiter_pass
      - MARIADB_DATABASE=test
    volumes:
      - um1_etc:/usr/local/mariadb/columnstore/etc
      - um1_mysql:/usr/local/mariadb/columnstore/mysql/db
      - um1_local:/usr/local/mariadb/columnstore/local
      - ./columnstore_um1:/docker-entrypoint-initdb.d
    networks:
      mcsnet:
        ipv4_address: 10.5.1.12
        aliases:
        - columnstore_host_nm
    ports:
      - "3306:3306"

  pm2:
    image: mariadb/columnstore:1.2
    environment:
      - MARIADB_CS_POSTCFG_INPUT=
    volumes:
      - dbroot2:/usr/local/mariadb/columnstore/data2
      - pm2_etc:/usr/local/mariadb/columnstore/etc
    networks:
      mcsnet:
        ipv4_address: 10.5.1.13

  pm1:
    image: mariadb/columnstore:1.2
    environment:
      - MARIADB_CS_POSTCFG_INPUT=2\n1\nn\ny\ncolumnstore-1\n1\n1\num1\n\n\n2\npm1\n\n\n1\npm2\n\n\n2\n
    depends_on:
      - um1
      - pm2
    volumes:
      - dbroot1:/usr/local/mariadb/columnstore/data1
      - pm1_etc:/usr/local/mariadb/columnstore/etc
    networks:
      mcsnet:
        ipv4_address: 10.5.1.14
  jupyter:
    image: mariadb/columnstore_jupyter:1.2
    command: start-notebook.sh --NotebookApp.password='sha1:817af87d3fe5:febd7d6959b12ee6839a26d56f8f54c88922e9c2'
    hostname: jupyter
    depends_on:
      - um1
      - pm1
      - pm2
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - um1_etc:/usr/local/mariadb/columnstore/etc

    networks:
      mcsnet:
        ipv4_address: 10.5.1.19

volumes:
  dbroot1:
  dbroot2:
  um1_mysql:
  um1_etc:
  pm1_etc:
  pm2_etc:
  um1_local:

networks:
  mcsnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.1.0/16
         gateway: 10.5.1.1
