language: bash
services: docker
env:
  - VERSION=columnstore

install:
  - git clone https://github.com/mariadb-corporation/mariadb-docker-images.git ~/mariadb-docker-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="mariadb/$VERSION"

script:
  - travis_retry docker build -t "$image" .
  - ~/mariadb-docker-images/test/run.sh "$image"
  - bash ./test/test.sh "$image"
after_script:
- docker images

